### ISSUE TITLE
Develop one snake game

### ISSUE THREAD

**Issue by cat2k22** [cat2k22/Hacktoberfest2022#10]

**Comment by iamAditya01** [comment]
assign me pls

**Comment by pranit9000** [comment]
please assign me @iamAditya01

**Comment by MoitreyoChak** [comment]
Hey , I am interested in this task. can you pls assign this to me?

**Comment by imNilabja** [comment]
I would like to do this task, can you assign me

**Comment by cat2k22** [comment]
ok, i will assign you.
